- name: dev.yml
  ansible.builtin.import_playbook: dev.yml
  tags: simba

- name: test.yml
  ansible.builtin.import_playbook: test.yml
  tags: simba

- name: prod.yml
  ansible.builtin.import_playbook: prod.yml
  tags: simba
