# init is not needed if you're only running on localhost!
# - hosts: localhost #, fedora, ubuntu
#   vars:
#     # Host_vars
#     ansible_become_password: u
#     ansible_user: "{{lookup('ansible.builtin.env', 'USER')}}"
#   roles:
#   - App

- name: engine.Simba .pre
  ansible.builtin.import_playbook: "{{ lookup('ansible.builtin.env', 'HOME') }}/src/bot/engine.Simba/src/install/ansible/pre.yml"
  
- name: engine.Simba prod()
  ansible.builtin.import_playbook: "{{ lookup('ansible.builtin.env', 'HOME') }}/src/bot/engine.Simba/src/install/ansible/uni.yml"
  