- hosts: localhost
  vars:
    uni: ".uni/"
    stor: "{{uni}}/stor/"
    vm: "{{uni}}/vm/"
    repo: [
      { subdir: "{{stor}}", repo: "git@github.com:UniStor/MinIO.git", name: "MinIO"},
      { subdir: "{{vm}}", repo: "git@github.com:Unicorn-OS/LXD.hyperion.git", name: "LXD.hyperion"},
      { subdir: "{{vm}}", repo: "git@github.com:Unicorn-OS/VirtualDisplay.git", name: "VirtualDisplay"},
      ]
  tasks:
  - debug:
      msg: "{{item.name}}"
    loop: "{{repo}}"

  - name: Git checkout
    ansible.builtin.git:
      repo: "{{item.repo}}"
      dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/src/{{item.subdir}}{{item.name}}"
    loop: "{{repo}}"
