localhost ansible_become_password=u ansible_connection=local

[test]
192.168.1.133

[test:vars]
ansible_user=me


[Chromebook]
192.168.1.139

[Chromebook:vars]
ansible_user=me
ansible_port=1066


[nodes:children]
test
Chromebook

[nodes:vars]
# use Vault or passwords
ansible_password=u
ansible_become_password=u
